
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  selector:
    matchLabels:
      component: elasticsearch
  template:
    metadata:
      labels:
        component: elasticsearch
    spec:
      securityContext:
        fsGroup: 1000  
        runAsUser: 0 
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
        env:
        - name: discovery.type
          value: single-node
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
      
        livenessProbe:
          httpGet:
            port: http
            path: _cluster/health
            
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            port: http
            path: _cluster/health
            
          initialDelaySeconds: 30
          periodSeconds: 10

        resources: 
          requests:
            
            memory: "1000Mi"
            cpu: "200m"
          limits:
           
            memory: "2000Mi"
            cpu: "500m"

            
       
          
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
          
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: esdata



# ---
# es exporter 

# helm install esporter prometheus-community/prometheus-elasticsearch-exporter

# https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-elasticsearch-exporter

# ---